SELECT PURCHASES.USER_ID, COUNT(ITEM) as PURCHASE_COUNT, SUM(PRICE) as TOTAL_PRICE
FROM ((GAME_USERS
LEFT JOIN PURCHASES ON GAME_USERS.ID = PURCHASES.USER_ID)
LEFT JOIN CHARACTERS ON PURCHASES.ITEM = CHARACTERS.NAME)
GROUP BY PURCHASES.USER_ID ORDER BY PURCHASES.USER_ID DESC